package com.digirati.elucidate.common.infrastructure.constants

object OAConstants {
    const val URI_ANNOTATED_BY = "http://www.w3.org/ns/oa#annotatedBy"
    const val URI_ANNOTATED_AT = "http://www.w3.org/ns/oa#annotatedAt"
    const val URI_SERIALIZED_BY = "http://www.w3.org/ns/oa#serializedBy"
    const val URI_SERIALIZED_AT = "http://www.w3.org/ns/oa#serializedAt"
    const val URI_ITEM = "http://www.w3.org/ns/oa#item"
    const val URI_VIA = "http://www.w3.org/ns/oa#via"
    const val URI_HAS_TARGET = "http://www.w3.org/ns/oa#hasTarget"
    const val URI_HAS_SELECTOR = "http://www.w3.org/ns/oa#hasSelector"
    const val URI_FRAGMENT_SELECTOR = "http://www.w3.org/ns/oa#FragmentSelector"
    const val URI_CONFORMS_TO = "http://purl.org/dc/terms/conformsTo"
    const val URI_HAS_SOURCE = "http://www.w3.org/ns/oa#hasSource"
    const val URI_EXACT = "http://www.w3.org/ns/oa#exact"
    const val URI_PREFIX = "http://www.w3.org/ns/oa#prefix"
    const val URI_SUFFIX = "http://www.w3.org/ns/oa#suffix"
    const val URI_END = "http://www.w3.org/ns/oa#end"
    const val URI_START = "http://www.w3.org/ns/oa#start"
    const val URI_CSS_SELECTOR = "http://www.w3.org/ns/oa#CssSelector"
    const val URI_XPATH_SELECTOR = "http://www.w3.org/ns/oa#XPathSelector"
    const val URI_TEXT_QUOTE_SELECTOR = "http://www.w3.org/ns/oa#TextQuoteSelector"
    const val URI_TEXT_POSITION_SELECTOR = "http://www.w3.org/ns/oa#TextPositionSelector"
    const val URI_DATA_POSITION_SELECTOR = "http://www.w3.org/ns/oa#DataPositionSelector"
    const val URI_SVG_SELECTOR = "http://www.w3.org/ns/oa#SvgSelector"
    const val URI_HAS_BODY = "http://www.w3.org/ns/oa#hasBody"
    const val URI_IS_REPLACED_BY = "http://www.w3.org/ns/oa#isReplacedBy"
}